apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dotnet-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnet-component
    app.kubernetes.io/part-of: e2e-dotnet
  name: dotnet-component
  namespace: e2e-demo-gtgz
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dotnet-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: dotnet-component
    spec:
      containers:
      - image: quay.io/codewindbtle/test-images:e47099936c5845bd9960e87578713791
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
